<?php echo form_open('procurement/Release_note?pro=save');?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p"></div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">New Release NOTE</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Release Note number will be automatically generated by the system.</div>
			<div class="ui-main-form-5">
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Information</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<div class="ui-main-form-1">
									<div class="middle_d">
										<table width="100%" class="ui-content-form-reg" style="">
											<tr >
												<td class="ui-desk-style-table">
													<table class="ui-content-form" width="100%" border="0">
														<tr>
															<td style="padding:10px;" valign="top" class="ui-w">Status  :</td>
														<?php if ($this->input->get('pro') == 'new' ){?>
														<td style="padding:10px;" valign="top">
															<?php
																$Status_list = array(
																		  '0' => 'Submitted',

																	   );
																 ?>
															<?php echo form_dropdown('n_Status_list', $Status_list ,'', 'class="dropdown n_wi-date2" style="display:inline-block; width:100px; height:30px;"'); ?>
															</td>
														<?php }elseif ($this->input->get('pro') == 'edit' ){?>
														<td style="padding:10px;" valign="top"> Send </td>
														<?php } ?>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Release Note Type :   </td>
															<td style="padding:10px;" valign="top"> MRIN </td>
														</tr>
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>FROM</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Contact Person :  </td>
															<td style="padding:10px;" valign="top"> <?=$this->session->userdata("v_UserName")?> </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Area  :  </td>
															<td style="padding:10px;" valign="top"> <?=$this->session->userdata("hosp_code")?> </td>
														</tr>
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>DELIVER TO</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Contact Person :  </td>
																<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding:10px;" valign="top"><div id="deliv"></div> </td>
																<?php }elseif ($this->input->get('pro') == 'edit' ){?>
																<td style="padding:10px;" valign="top"> <?=$rndet[0]->rep;?>  </td>
																<?php } ?>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Area  :  </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding:10px;" valign="top">

															<?php
																$Area_list = array(
																		  'IIUM' => 'IIUM',
																		  'MKA' => 'MKA',

																	   );
																 ?>
															<?php echo form_dropdown('n_Area_list', $listh ,'', 'class="dropdown n_wi-date2"  onchange="getval(this.value);" style="display:inline-block; width:100px; height:30px;"'); ?> </td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding:10px;" valign="top"> <?=$rndet[0]->hosp;?> </td>
															<?php } ?>
														</tr>
													</table>
												</td>
											</tr>
										</table>
									</div>
								</div>
								<div class="ui-main-form-2">
									<div class="middle_d">
										<table class="ui-content-form-reg">
											<tr >
												<td class="ui-desk-style-table">
													<table class="ui-content-form" style="color:black;" width="100%" border="0">
														<tr>
															<td style="padding-left:10px;" valign="top" colspan="2"><u>SHIPPING INFO</u>  </td>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top" class="ui-w">Shipment Type  :  </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding-left:10px;" valign="top">
															<?php
																$Shipment_list = array(
																		  '0' => 'Courier',
																		  '1' => 'By hand',

																	   );
																 ?>
															<?php echo form_dropdown('n_Shipment_list', $Shipment_list ,'', 'class="dropdown n_wi-date2" style="display:inline-block; width:100px; height:30px;"'); ?> </td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding:10px;" valign="top"> <?=$rndet[0]->sh_type;?> </td>
															<?php } ?>

														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Courier Company  :  </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding-left:10px;" valign="top">
															<?php
																$Courier_list = array(
																		  '0' => 'Other',
																		  '1' => 'ABX',
																		  '2' => 'CityLink',
																		  '3' => 'DHL',

																	   );
																 ?>
															<?php echo form_dropdown('n_Courier_list', $Courier_list ,'', 'class="dropdown n_wi-date2" style="display:inline-block; width:100px; height:30px;"'); ?> </td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding:10px;" valign="top"> <?=$rndet[0]->courier;?> </td>
															<?php } ?>

														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Consignment Note :    </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding:10px;" valign="top"> <input type="text" name="consignment_note"  value="" class="form-control-button2 n_wi-date2"></td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding:10px;" valign="top"><?=$rndet[0]->consignment_note;?></td>
															<?php } ?>
														</tr>
														<tr>
															<td style="padding:10px;" valign="top">Consignment Date :    </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
															<td style="padding:10px;" valign="top"> <input type="text" name="consignment_date"  value="" id="date0" class="form-control-button2 n_wi-date2" readonly></td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding:10px;" valign="top"> <?=date('d/m/Y',strtotime($rndet[0]->consignment_date));?></td>
															<?php } ?>
														</tr>
														<tr>
															<td style="padding-left:10px;" class="ui-w" valign="top">Accessories  :   </td>
															<?php if ($this->input->get('pro') == 'new' ){?>
														    <td style="padding-left:10px;" ><textarea class="Input n_com2" name="accessories"></textarea></td>
															<?php }elseif ($this->input->get('pro') == 'edit' ){?>
															<td style="padding-left:10px;" ><textarea class="Input n_com2" name="accessories"><?=$rndet[0]->accessories;?></textarea></td>
															<?php } ?>
														</tr>
													</table>
												</td>
											</tr>
										</table>
									</div>
								</div>
							</td>
						</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Item Specification</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<?php if ($this->input->get('pro') == 'new' ){?>
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td  valign="top" style="text-align:right;">Item(s)   :   </td>
										<td style="padding-top:30px;"><table class="wnctable" border="1" style="text-align:center;">
									<tr>
										<th>No</th>
										<th>Item Code</th>
										<th>Item Name</th>
										<th>MRIN Ref No.</th>
										<th>Qty Req</th>
										<th>Qty In-Store</th>
										<th>Qty Release</th>
									</tr>
									<tbody id="live_data">
		</tbody>                   </tbody>
								</table></td>
									</tr>
								</table>
								<?php }elseif ($this->input->get('pro') == 'edit' ){?>
								<style>table.wnctable th {background:#66b2b2 ;}</style>
								<table class="wnctable" border="1" style="text-align:center; margin:5px auto;" align="center">
									<tr>
										<th>No</th>
										<th>Item Code</th>
										<th>Item Name</th>
										<th>MRIN Ref No.</th>
										<th>Qty Release</th>
									</tr>
									<?=$i=1;foreach($rnitem as $row){;?>
									<tr>
										<td><?=$i++;?></td>
										<td><b><?=$row->Item_code;?></b></a>&nbsp;</td>
										<td><b><?=$row->ItemName;?></b></a>&nbsp;</td>
										<td><b><?=$row->MRIN_No;?></b></a>&nbsp;</td>
										<td class=""><b><?=$row->Qty?></b></a>&nbsp;</td>
									</tr>
									<?php } ?>
								</table>
								<?php } ?>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center">
						<input type="submit" class="btn-button btn-primary-button" name="mysubmit" value="Save" style="width:150px;"/>
						<input type="button" class="btn-button btn-primary-button" name="Cancel" value="Cancel" onclick="window.history.back()" style="width:150px;"/>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<style>
	.icon{
	 font-size:14px;
	 margin-right:5px;
	 margin-left:5px;
	 color:red;
	 display:iniline-block;
	}
	.icon2{
	 font-size:14px;
	 margin-left:5px;
	 color:green;
	}
</style>
</body>
<?php include 'content_jv_popup.php';?>
<?php echo form_close(); ?>
</html>
<script>
	  $( document ).ready(function() {
getval('IIUM');
});

function getval(sel)
{
	var h = sel;
        $.ajax({
                url:"<?php echo base_url('index.php/ajax/itemrnt'); ?>",
                method:"POST",
				data:{hosp_code:h},
                dataType:"text",
                success:function(data){
                $('#live_data').html(data);
			     getrep(h);
                }
           });

}

function getrep(sel)
{
	var h = sel;
 $.ajax({
                url:"<?php echo base_url('index.php/ajax/get_rep'); ?>",
                method:"POST",
				data:{hosp_code:h},
                dataType:"text",
                success:function(data){

			   $('#deliv').text(data);
                }
           });
}

</script>
