<?php echo form_open('vendor_reg_ctrl/confirmation');?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p">&nbsp;</div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">Confirm Vendor Register</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Vendor Code will be automatically generated by the system.<br> <span style="color:red;"><?php echo validation_errors(); ?></span></div>
			<div class="ui-main-form-1">
				<div class="middle_d">
					<table width="100%" class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Vendor Details</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding-left:10px; padding-top:5px;" valign="top" class="ui-w">Service Code:</td>
											<td style="padding-left:10px; padding-top:5px;" valign="top"> <input type="text" name="n_service_code" value="<?php echo set_value('n_service_code',$this->session->userdata('usersess')); ?>" class="form-control-button2 n_wi-date2 input-none" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px; padding-top:5px;" valign="top" class="ui-w">Vendor Code:</td>
											<td style="padding-left:10px; padding-top:5px;" valign="top"> <input type="text" name="n_vendor_code" value="<?php echo set_value('n_vendor_code'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Vendor Name :   </td>
											<td style="padding-left:10px;" valign="top"><input type="text" name="n_vendor_name" value="<?php echo set_value('n_vendor_name'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Grading Date :   </td>
											<td style="padding-left:10px;" valign="top"><input type="date" name="n_grading_date" value="<?php echo set_value('n_grading_date'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Region :   </td>
											<td style="padding-left:10px;" valign="top"><?php 
										$Region = array(
											'' => '',
										'HQKL' => 'HQKL',
										'NRTH' => 'NRTH',
                  						'STH' => 'STH',
                  				 		'BBB' => 'BBB',
                  				 		'BRI' => 'BRI',
                  						'SJOH' => 'SJOH',
                  				 		'PMC' => 'PMC',
                					 );
										 ?>
										  <?php echo form_dropdown('n_region', $Region, set_value('n_region'), 'class="dropdown n_wi-date2" disabled'); ?> </td>
										</tr>
										<!--<tr>
											<td style="padding-left:10px;" valign="top">Action Flag :  </td>
											<td style="padding-left:10px;" valign="top"><?php 
										$Action = array(
										'I' => 'I',
										'U' => 'U',
                  						'D' => 'D',
                					 );
										 ?>
										  <?php echo form_dropdown('n_region', $Action, set_value('n_region'), 'class="dropdown n_wi-date2" disabled'); ?>
											</td>
										</tr>-->
										<tr>
											<td style="padding-left:10px;" valign="top">Group Register :  </td>
											<td style="padding-left:10px;" valign="top"><?php 
										$Group_Register = array(
											'' => '',
										'NON' => 'NON',
										'CLA' => 'CLA',
                  						'CLB' => 'CLB',
                					 );
										 ?>
										  <?php echo form_dropdown('n_group_register', $Group_Register, set_value('n_group_register'), 'class="dropdown n_wi-date2" disabled'); ?>
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Grade :  </td>
											<td style="padding-left:10px;" valign="top">	
												<input type="radio" id="radio-1-1" name="n_Grade" class="regular-radio" value="G1" disabled <?php echo set_radio('n_Grade', 'G1',TRUE); ?> />   
												<label for="radio-1-1"></label> G1<br>
												<input type="radio" id="radio-1-2" name="n_Grade" class="regular-radio" value="G2" disabled <?php echo set_radio('n_Grade', 'G2'); ?>/>  
												<label for="radio-1-2"></label> G2<br>
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Vendor Email :   </td>
											<td style="padding-left:10px;" valign="top"><input type="email" name="n_vendor_email" value="<?php echo set_value('n_vendor_email'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Page No :   </td>
											<td style="padding-left:10px;" valign="top"><input type="email" name="n_pageno" value="<?php echo set_value('n_pageno'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Url :   </td>
											<td style="padding-left:10px;" valign="top"><input type="email" name="n_url" value="<?php echo set_value('n_url'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
										</tr>																																			
									</table>
								</td>
							</tr>
					</table>
				</div>
				
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Payment Detail</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding-left:10px; padding-top:5px;" valign="top" class="ui-w">Currency:</td>
										<td style="padding-left:10px; padding-top:5px;" valign="top"> <?php 
										$Payment = array(
											'' => '',
										'RM' => 'RM',
										'USD' => 'USD',
                  						'SD' => 'SD',
                  				 		'AUD' => 'AUD',
                					 );
										 ?>
										  <?php echo form_dropdown('n_currency', $Payment, set_value('n_currency'), 'class="dropdown n_wi-date2" disabled'); ?> 
										 </td>
									</tr>
									<tr>
											<td style="padding-left:10px;" valign="top">Payment :  </td>
											<td style="padding-left:10px;" valign="top">
											<?php 
										$Payment = array(
										'' => '',
										'CHEQ' => 'CHEQ',
                  						'LOC' => 'LOC',
                  				 		'TT' => 'TT',
                  				 		'CPBD' => 'CPBD',
                  						'COD' => 'COD',
                  				 		'BC' => 'BC',
                					 );
										 ?>
										  <?php echo form_dropdown('n_payment', $Payment, set_value('n_payment'), 'class="dropdown n_wi-date2" disabled'); ?> 
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Terms :  </td>
											<td style="padding-left:10px;" valign="top">	
												<input type="radio" id="radio-1-4" name="n_terms" class="regular-radio" value="Credit" disabled<?php echo set_radio('n_terms', 'Credit',TRUE); ?>/>   
												<label for="radio-1-4"></label> Credit<br>
												<input type="radio" id="radio-1-5" name="n_terms" class="regular-radio" value="Cash" disabled<?php echo set_radio('n_terms', 'Cash'); ?>/>  
												<label for="radio-1-5"></label> Cash<br>
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Terms Mode:  </td>
											<td style="padding-left:10px;" valign="top">	
												<input type="radio" id="radio-1-6" name="n_terms_mode" class="regular-radio" value="30" disabled<?php echo set_radio('n_terms_mode', '30',TRUE); ?>/>   
												<label for="radio-1-6"></label> 30<br>
												<input type="radio" id="radio-1-7" name="n_terms_mode" class="regular-radio" value="60" disabled<?php echo set_radio('n_terms_mode', '60'); ?>/>  
												<label for="radio-1-7"></label> 60<br>
											</td>
										</tr>																									
								</table>
							</td>
						</tr>						
					</table>
				</div>

			</div>
			<div class="ui-main-form-2">
				<div class="middle_d">
					<table class="ui-content-form-reg" >
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Details of Related Vendor</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Contact Name : </td>
										<td style="padding-left:10px;" ><input type="text" name="n_contact" value="<?php echo set_value('n_contact'); ?>" class="form-control-button n_wi-date2" disabled></td>
									</tr>
									<tr>
											<td style="padding-left:10px;" valign="top">Company Type :  </td>
											<td style="padding-left:10px;" valign="top">
											<?php 
										$Company_Type = array(
											'' => '',
										'SP' => 'SP',
										'SBHD' => 'SBHD',
                  						'PT' => 'PT',
                  				 		'BD' => 'BD',
                  				 		'SMHD' => 'SMHD',
                					 );
										 ?>
										  <?php echo form_dropdown('n_company_type', $Company_Type, set_value('n_company_type'), 'class="dropdown n_wi-date2" disabled'); ?> 
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Vendor Type :  </td>
											<td style="padding-left:10px;" valign="top">
											<?php 
										$Vendor_Type = array(
											'' => '',
										'COM' => 'COM',
										'PMSB' => 'PMSB',
                  						'MOH' => 'MOH',
                					 );
										 ?>
										  <?php echo form_dropdown('n_vendor_type', $Vendor_Type, set_value('n_vendor_type'), 'class="dropdown n_wi-date2" disabled'); ?> 
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Register Type:  </td>
											<td style="padding-left:10px;" valign="top">	
												<input type="radio" id="radio-1-8" name="n_register_type" class="regular-radio" value="BUMI" disabled<?php echo set_radio('n_register_type', 'BUMI',TRUE); ?>/>   
												<label for="radio-1-8"></label> Bumi<br>
												<input type="radio" id="radio-1-9" name="n_register_type" class="regular-radio" value="NON BUMI" disabled<?php echo set_radio('n_register_type', 'NON BUMI'); ?>/>  
												<label for="radio-1-9"></label> Non Bumi<br>
											</td>
										</tr><tr>
											<td style="padding-left:10px;" valign="top">Remark :  </td>
											<td style="padding-left:10px;" valign="top"><textarea class="Input n_com2" name="n_remark" cols="17" rows="6" disabled><?php echo set_value('n_remark'); ?></textarea></td>
										</tr>																																									
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Location</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table" style="padding-bottom: 8px;">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" valign="top">Hand-phone Nombor :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_hand_phone_nombor" value="<?php echo set_value('n_hand_phone_nombor'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Phone Nombor :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_phone_nombor" value="<?php echo set_value('n_phone_nombor'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Fax Nombor :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_fax_nombor" value="<?php echo set_value('n_fax_nombor'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Address :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_Address" value="<?php echo set_value('n_Address'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Address 2 :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_Address_2" value="<?php echo set_value('n_Address_2'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Address 3 :   </td>
										<td style="padding-left:10px;" valign="top"><input type="text" name="n_Address_3" value="<?php echo set_value('n_Address_3'); ?>" class="form-control-button2 n_wi-date2" disabled></td>
									</tr>									
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center"><input type="submit" class="btn-button btn-primary-button" name="mysubmit" value="Save" style="width:150px;"/>
					<input type="button" class="btn-button btn-primary-button" name="Cancel" value="Cancel" onclick="window.history.back()" style="width:150px;"/></td>
				</tr>
			</table>
			<?php echo form_hidden('m',$this->input->post('m')) ?>
			<?php echo form_hidden('y',$this->input->post('y')) ?>
			<?php echo form_hidden('n_service_code',$this->input->post('n_service_code'));?>
			<?php echo form_hidden('n_vendor_code',$this->input->post('n_vendor_code'));?>
			<?php echo form_hidden('n_vendor_name',$this->input->post('n_vendor_name'));?>
			<?php echo form_hidden('n_grading_date',$this->input->post('n_grading_date'));?>
			<?php echo form_hidden('n_region',$this->input->post('n_region'));?>
			<?php echo form_hidden('n_group_register',$this->input->post('n_group_register'));?>
			<?php echo form_hidden('n_Grade',$this->input->post('n_Grade'));?>
			<?php echo form_hidden('n_vendor_email',$this->input->post('n_vendor_email'));?>
			<?php echo form_hidden('n_pageno',$this->input->post('n_pageno'));?>
			<?php echo form_hidden('n_url',$this->input->post('n_url'));?>
			<?php echo form_hidden('n_currency',$this->input->post('n_currency'));?>
			<?php echo form_hidden('n_payment',$this->input->post('n_payment'));?>
			<?php echo form_hidden('n_terms',$this->input->post('n_terms'));?>
			<?php echo form_hidden('n_terms_mode',$this->input->post('n_terms_mode'));?>
			<?php echo form_hidden('n_contact',$this->input->post('n_contact'));?>
			<?php echo form_hidden('n_company_type',$this->input->post('n_company_type'));?>
			<?php echo form_hidden('n_vendor_type',$this->input->post('n_vendor_type'));?>
			<?php echo form_hidden('n_register_type',$this->input->post('n_register_type'));?>
			<?php echo form_hidden('n_remark',$this->input->post('n_remark'));?>
			<?php echo form_hidden('n_hand_phone_nombor',$this->input->post('n_hand_phone_nombor'));?>
			<?php echo form_hidden('n_phone_nombor',$this->input->post('n_phone_nombor'));?>
			<?php echo form_hidden('n_fax_nombor',$this->input->post('n_fax_nombor'));?>
			<?php echo form_hidden('n_Address',$this->input->post('n_Address'));?>
			<?php echo form_hidden('n_Address_2',$this->input->post('n_Address_2'));?>
			<?php echo form_hidden('n_Address_3',$this->input->post('n_Address_3'));?>
		</div>
	</div>
</div>
</body>
<?php include 'content_jv_popup.php';?>
<?php echo form_close(); ?>
</html>
