<?php echo form_open('bems_desk_ctrl');?>
<?php $numberdate = 0; ?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p">&nbsp;</div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">New Complaint</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Complaint number will be automatically generated by the system.<br> <span style="color:red;"><?php echo validation_errors(); ?></span></div>
			<div class="ui-main-form-1">
				<?php $RN="RQ/A4/B01714/14";
				echo form_hidden('RN');?>
				<div class="middle_d">
					<table width="100%" class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Details</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">*Requested By :</td>
										<td style="padding-left:10px;" ><input type="text" name="n_requested_by" value="<?php echo set_value('n_requested_by'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">*Complaint Date : </td>
										<td style="padding-left:10px;"><input type="text"  id="date<?php echo $numberdate++; ?>" name="n_complaint_date" max="<?=date('Y-m-d')?>" value="<?php echo set_value('n_complaint_date'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">*Complaint Time :</td>
										
										<td style="padding-left:10px;"><input type="time" name="n_complaint_time" value="<?php echo set_value('n_complaint_time',date("H:i")); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">*Designation : </td>
										<td style="padding-left:10px;" valign="top">	
											<input type="radio" id="radio-1-1" name="n_designation" class="regular-radio" value = "Doctor" <?php echo set_radio('n_designation', 'Doctor', TRUE); ?> />   
											<label for="radio-1-1"></label> Doctor<br>
											<input type="radio" id="radio-1-2" name="n_designation" class="regular-radio" value = "Matron" <?php echo set_radio('n_designation', 'Matron'); ?>/>   
											<label for="radio-1-2"></label> Matron<br>
											<input type="radio" id="radio-1-3" name="n_designation" class="regular-radio" value = "Medical Assistant" <?php echo set_radio('n_designation', 'Medical Assistant'); ?>/>   
											<label for="radio-1-3"></label> Medical Assistant<br>
											<input type="radio" id="radio-1-4" name="n_designation" class="regular-radio" value = "IIUM Officer" <?php echo set_radio('n_designation', 'IIUM Officer'); ?>/>   
											<label for="radio-1-4"></label> IIUM Officer<br>
											<input type="radio" id="radio-1-5" name="n_designation" class="regular-radio" value = "Sister In-Charge" <?php echo set_radio('n_designation', 'Sister In-Charge'); ?>/>   
											<label for="radio-1-5"></label> Sister In-Charge<br>
											<input type="radio" id="radio-1-6" name="n_designation" class="regular-radio" value = "Sister On Duty" <?php echo set_radio('n_designation', 'Sister On Duty'); ?>/>   
											<label for="radio-1-6"></label> Sister On Duty<br>
											<input type="radio" id="radio-1-7" name="n_designation" class="regular-radio" value = "Specialist" <?php echo set_radio('n_designation', 'Specialist'); ?>/>   
											<label for="radio-1-7"></label> Specialist<br>
											<input type="radio" id="radio-1-8" name="n_designation" class="regular-radio" value = "Staff Nurse" <?php echo set_radio('n_designation', 'Staff Nurse'); ?>/>   
											<label for="radio-1-8"></label> Staff Nurse<br>
											<input type="radio" id="radio-1-9" name="n_designation" class="regular-radio" value = "Supervisor" <?php echo set_radio('n_designation', 'Supervisor'); ?>/>   
											<label for="radio-1-9"></label> Supervisor<br>
											<input type="radio" id="radio-1-10" name="n_designation" class="regular-radio" value = "APSB" <?php echo set_radio('n_designation', 'APSB'); ?>/>   
											<label for="radio-1-10"></label> APSB<br>
											<input type="radio" id="radio-1-11" name="n_designation" class="regular-radio" value = "PMSB" <?php echo set_radio('n_designation', 'PMSB'); ?>/>   
											<label for="radio-1-11"></label> PMSB<br>
											<input type="radio" id="radio-1-12" name="n_designation" class="regular-radio" value = "APFMS" <?php echo set_radio('n_designation', 'APFMS'); ?>/>   
											<label for="radio-1-12"></label> APFMS<br>
										</td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">*Priority :  </td>
										<td style="padding-left:10px;" valign="top">	
											<input type="radio" id="radio-1-13" name="n_priority" class="regular-radio"  value = "Normal" <?php echo set_radio('n_priority', 'Normal',TRUE); ?>/>   
											<label for="radio-1-13"></label> Normal<br>
											<input type="radio" id="radio-1-14" name="n_priority" class="regular-radio" value = "Emergency" <?php echo set_radio('n_priority', 'Emergency'); ?>/>   
											<label for="radio-1-14"></label><span style="color:red;"> Emergency</span><br>
										</td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">*Source :  </td>
										<td style="padding-left:10px;" valign="top">	
										<input type="radio" id="radio-1-15" name="n_source" onclick="javascript:fShowSource('N');" class="regular-radio" value = "IIUM"<?php echo set_radio('n_source', 'IIUM',TRUE); ?>/>   
										<label for="radio-1-15"></label> IIUM<br>
										<input type="radio" id="radio-1-16" name="n_source" onclick="javascript:fShowSource('Y');" class="regular-radio" value = "PMSB"<?php echo set_radio('n_source', 'PMSB'); ?>/>   
										<label for="radio-1-16"></label> PMSB<br>
										</td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">NCR No : </td>
										<?php if ($this->input->post('n_source') == 'PMSB') { ?>
										<td><input type="text" id="n_ncr_no" name="n_ncr_no" style="display:block;" value="<?php echo set_value('n_ncr_no'); ?>" class="form-control-button n_wi-date2"></td>
										<?php } else { ?>
										<td><input type="text" id="n_ncr_no" name="n_ncr_no" style="display:none;" value="" class="form-control-button n_wi-date2"></td>
										<?php } ?>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">VCM Month :  </td>
										<?php if ($this->input->post('n_source') == 'PMSB') { ?>
										<td><input type="text" id="vcm_month" name="vcm_month" style="display:block;" value="<?php echo set_value('vcm_month'); ?>" class="form-control-button n_wi-date2"></td>
										<?php } else { ?>
										<td><input type="text" id="vcm_month" name="vcm_month" style="display:none;" value="" class="form-control-button n_wi-date2"></td>
										<?php } ?>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">VCM Year :   </td>
										<?php if ($this->input->post('n_source') == 'PMSB') { ?>
										<td><input type="text" id="vcm_year" name="vcm_year" style="display:block;" value="<?php echo set_value('vcm_year'); ?>" class="form-control-button n_wi-date2"></td>
										<?php } else { ?>
										<td><input type="text" id="vcm_year" name="vcm_year" style="display:none;" value="" class="form-control-button n_wi-date2"></td>
										<?php } ?>
									</tr>	
									<tr>
										<td style="padding-left:10px;" valign="top">*Summary : </td>
										<td style="padding-left:10px;"><textarea name="n_summary"  class="input n_com2"><?php echo set_value('n_summary'); ?></textarea></td>
									</tr>	
									<tr>
										<td style="padding-left:10px;" valign="top">*Description : </td>
										<td style="padding-left:10px;"><textarea class="input n_com2" name="n_description"><?php echo set_value('n_description'); ?></textarea></td>
									</tr>																																						
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Follow Up Information</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">*Personnel Code :   </td>
										<td style="padding-left:10px;" ><input type="text" id="n_personnel_code" name="n_personnel_code" value="<?php echo set_value('n_personnel_code'); ?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fCallassetdetailname(this)" value=""></span>
									</tr>
									<tr>
										<td style="padding-left:10px;">*Personnel Name :   </td>
										<td style="padding-left:10px;"><input type="text" id="n_personnel_name" name="n_personnel_name" value="<?php echo set_value('n_personnel_name'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Designation :  </td>
										<td style="padding-left:10px;"><input type="text" id="n_Desig" name="n_Desig" value="<?php echo set_value('n_Desig'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">*Start Date : </td>
										<td style="padding-left:10px;"><input type="text"  id="date<?php echo $numberdate++; ?>" name="n_startdate" value="<?php echo set_value('n_startdate'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">*Start Time :   </td>
										<td style="padding-left:10px;"><input type="time" name="n_starttime" value="<?php echo set_value('n_starttime'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">*End Date :   </td>
										<td style="padding-left:10px;"><input type="text"  id="date<?php echo $numberdate++; ?>" name="n_enddate" value="<?php echo set_value('n_enddate'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>	
									<tr>
										<td style="padding-left:10px;">*End Time :   </td>
										<td style="padding-left:10px;"><input type="time" name="n_endtime" value="<?php echo set_value('n_endtime'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Action Taken :  </td>
										<td style="padding-left:10px;"><textarea class="input n_com2" name="n_actiontaken"><?php echo set_value('n_actiontaken'); ?></textarea></td>
									</tr>																																																																	
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<div class="ui-main-form-2">
				<div class="middle_d">
					<table class="ui-content-form-reg" >
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Details of Related Request</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding-left:10px;" class="ui-w">Request Number : </td>
											<td style="padding-left:10px;" ><input type="text" id="n_request_number" name="n_request_number" value="<?php echo set_value('n_request_number'); ?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fCallR_number()"></span></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Request Status :  </td>
											<td style="padding-left:10px;"><input type="text" id="n_request_status" name="n_request_status" value="<?php echo set_value('n_request_status'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Requested By : </td>
											<td style="padding-left:10px;"><input type="text" id="n_requested_by2" name="n_requested_by2" value="<?php echo set_value('n_requested_by2'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Requested Date : </td>
											<td style="padding-left:10px;"><input type="text" id="n_requested_date" name="n_requested_date" value="<?php echo set_value('n_requested_date'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Priority : </td>
											<td style="padding-left:10px;"><input type="text" id="n_priority2" name="n_priority2" value="<?php echo set_value('n_requested_date'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Summary : </td>
											<td style="padding-left:10px;"><textarea class="input n_com2" id="n_summary2" name="n_summary2" readonly><?php echo set_value('n_summary2'); ?></textarea></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Asset Tag Number : </td>
											<td style="padding-left:10px;"><input type="text" id="n_asset_tag_number" name="n_asset_tag_number" value="<?php echo set_value('n_asset_tag_number'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">*Asset Number :  </td>
											<td style="padding-left:10px;"><input type="text" id="n_asset_no" name="n_asset_no" value="<?php echo set_value('n_asset_no'); ?>" class="form-control-button  n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Asset Serial Number : </td>
											<td style="padding-left:10px;"><input type="text" id="n_asset_serial_number" name="n_asset_serial_number" value="<?php echo set_value('n_asset_serial_number'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Phone Number : </td>
											<td style="padding-left:10px;"><input type="text" id="n_phone_numberat" name="n_phone_numberat" value="<?php echo set_value('n_phone_numberat'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">User Department : </td>
											<td style="padding-left:10px;"><input type="text" id="n_user_department3" name="n_user_department2" value="<?php echo set_value('n_user_department2'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>	
										<tr>
											<td style="padding-left:10px;">Location :  </td>
											<td style="padding-left:10px;"><input type="text" id="n_location3" name="n_location2" value="<?php echo set_value('n_location2'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>	
										<tr>
											<td style="padding-left:10px;">Request Closed On : </td>
											<td style="padding-left:10px;"><input type="text" id="n_request_closed_on" name="n_request_closed_on" value="<?php echo set_value('n_request_closed_on'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>																																								
									</table>
								</td>
							</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Location</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table" style="padding-bottom: 8px;">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Phone Number :  </td>
										
									  <td style="padding-left:10px;" ><input type="text" name="n_phone_number" id="n_phone_number" value="<?php echo set_value('n_phone_number'); ?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fpop_location_user()"></td>
									</tr>
										<td style="padding-left:10px;">User Department :   </td>
										<td style="padding-left:10px;"><input type="text" id="n_user_department" name="n_user_department" value="<?php echo set_value('n_user_department'); ?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fCalllocation()"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" id="n_user_department1" name="n_user_department1" value="<?php echo set_value('n_user_department1'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Location : </td>
										<td style="padding-left:10px;"><input type="text" id="n_location" name="n_location" value="<?php echo set_value('n_location'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" id="n_location2" name="n_location1" value="<?php echo set_value('n_location1'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>																																					
								</table>
							</td>
						</tr>						
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr style="color:white;" height="30px">
								<td colspan="2" class="ui-header-new"><b>Related Asset</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding-left:10px;" class="ui-w">Asset Number :  </td>
											<td style="padding-left:10px;" ><input type="text" id="n_asset_number" name="n_asset_number" value="<?php echo set_value('n_asset_number'); ?>" class="form-control-button2 n_wi-eq3" readonly> <span href="" class="icon-windows" onclick="fCallassetsnumber(this)" value=""></span></td>

										</tr>
										<tr>
											<td style="padding-left:10px;">Tag Number :   </td>
											<td style="padding-left:10px;"><input type="text" id="n_tag_number" name="n_tag_number"  value="<?php echo set_value('n_tag_number'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Serial Number :  </td>
											<td style="padding-left:10px;"><input type="text" id="n_serial_number" name="n_serial_number" value="<?php echo set_value('n_serial_number'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;">Name :	 </td>
											<td style="padding-left:10px;"><input type="text" id="n_name" name="n_name" value="<?php echo set_value('n_name'); ?>" class="form-control-button n_wi-date2" readonly></td>
										</tr>																																						
									</table>
								</td>
							</tr>						
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Closing</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Close Date :    </td>
										<td style="padding-left:10px;" ><input type="text"  id="date<?php echo $numberdate++; ?>" name="n_close_date" value="<?php echo set_value('n_close_date'); ?>" class="form-control-button2 n_wi-date2" ></td>
									</tr>																																																													
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<?php echo form_hidden('parent',$this->input->get('parent'));?>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center"><input type="submit" class="btn-button btn-primary-button" style="width: 200px;" name="mysubmit" value="Confirm"></td>
				</tr>
			</table>
		</div>
	</div>
</div>
</form>
<?php include 'content_jv_popup.php';?>
<script language="javascript" type="text/javascript">
	function fShowSource(sTest)
	{
		if (sTest == "Y")
			{
				document.getElementById('n_ncr_no').style.display = "block"
				document.getElementById('vcm_month').style.display = "block"
				document.getElementById('vcm_year').style.display = "block"
				
			}
		
		else
			{
				document.getElementById('n_ncr_no').style.display = "none"
				document.getElementById('vcm_month').style.display = "none"
				document.getElementById('vcm_year').style.display = "none"
				document.getElementById("n_ncr_no").value = ""
				document.getElementById("vcm_month").value = ""
				document.getElementById("vcm_year").value = ""
			}
	}
</script>
</body>
<?php echo form_close(); ?>
</html>
