
<?php 
if($this->input->get('pro') == 'new'){ 
echo form_open('mrinnew_ctrl?pro=new');
}
else if($this->input->get('pro') == 'edit'){
echo form_open('mrinnew_ctrl?pro=edit&mrinno='.$this->input->get('mrinno'));
}?>


<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p"></div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;"><?php if($this->input->get('pro') == 'new'){?>New<?php }else{ ?>Edit<?php } ?> MRIN</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">MRIN number will be automatically generated by the system.</div>
			<div class="ui-main-form-1">
				<div class="middle_d">
					<table width="100%" class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Details</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding:10px;" valign="top" class="ui-w">Hospital :</td>
											<td style="padding:10px;" valign="top">IIUM Medical Hospital</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Date Issue :   </td>
											<td style="padding-left:10px;" valign="top"> <input type="text" name="n_date"  value="<?=set_value('n_date',isset($record[0]->DateCreated) ? date("d-m-Y",strtotime($record[0]->DateCreated)) : '')?>" id="date0" class="form-control-button2 n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Case  :   </td>
											<td style="padding-left:10px;" valign="top">
												<?php $num = 1; $num2 = 1?>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="0"<?=set_radio('n_Case','0',TRUE)?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 0 ? 'checked' : 'checked' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> BM<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="1"<?=set_radio('n_Case','1')?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 1 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> PPM<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="2"<?=set_radio('n_Case','2')?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 2 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> Stock<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="3"<?=set_radio('n_Case','3')?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 3 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> Vendor<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="4"<?=set_radio('n_Case','4')?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 4 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> RW<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Case" class="regular-radio" value="5"<?=set_radio('n_Case','5')?><?=isset($record[0]->ReqCase) && $record[0]->ReqCase == 5 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> LS<br>
												
											</td>
										</tr>-->
										<tr>
											<td style="padding-left:10px;" valign="top">Contract :  </td>
											<td style="padding-left:10px;" valign="top">
											<input type="radio" id="radio-1-<?=$num++?>" name="n_Contract" class="regular-radio" value="0"<?=set_radio('n_Contract','0',TRUE)?><?=isset($record[0]->ContractStatus) && $record[0]->ContractStatus == 0 ? 'checked' : 'checked' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> Comprehensive<br>
												<input type="radio" id="radio-1-<?=$num++?>" name="n_Contract" class="regular-radio" value="1"<?=set_radio('n_Contract','1')?><?=isset($record[0]->ContractStatus) && $record[0]->ContractStatus == 1 ? 'checked' : '' ?>/>   
												<label for="radio-1-<?=$num2++?>"></label> Non-Comprehensive<br>
											</td>
										</tr>																																		
									</table>
								</td>
							</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Root Cause of Breakdown</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Possible Failure of Complaint / Error / Problem Statement : </td>
										<td style="padding-left:10px;"><textarea class="Input n_com2" name="n_complaint"><?=set_value('n_complaint',isset($record[0]->rone) ? $record[0]->rone : '')?></textarea></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Finding: <br/>i)Process of Troubleshooting <br/>ii) Action Taken </td>
										<td style="padding-left:10px;"><textarea class="Input n_com2" name="n_troubleshooting"><?=set_value('n_troubleshooting',isset($record[0]->rtwo) ? $record[0]->rtwo : '')?></textarea></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Possible Root Cause of Finding </td>
										<td style="padding-left:10px;"><textarea class="Input n_com2" name="n_finding"><?=set_value('n_finding',isset($record[0]->rthree) ? $record[0]->rthree : '')?></textarea></td>
									</tr>									
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<div class="ui-main-form-2">
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Comments</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w" valign="top">Comments :   </td>
										<td style="padding-left:10px;" ><textarea class="Input n_com2" name="n_comment"><?=set_value('n_comment',isset($record[0]->Comments) ? $record[0]->Comments : '')?></textarea></td>
									</tr>																																																														
								</table>
							</td>
						</tr>						
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" >
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Root Cause of Breakdown</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Request Number : </td>
										<td style="padding-left:10px;"><input type="text" name="n_request" id="n_request" value="<?=set_value('n_request',isset($record[0]->WorkOfOrder) ? $record[0]->WorkOfOrder : '')?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="pop_requests(this)" value="Norequest" id="pop_requests"></span></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Requested Date : </td>
										<td style="padding-left:10px;"><input type="text" name="n_requested" id="n_requested" value="<?=set_value('n_requested',isset($record[0]->D_date) ? date("d-m-Y",strtotime($record[0]->D_date)) : '')?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Summary  : </td>
										<td style="padding-left:10px;"><textarea class="Input n_com2" name="n_summary" id="n_summary" readonly><?=set_value('n_summary',isset($record[0]->V_summary) ? $record[0]->V_summary : '')?></textarea></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Brand / Manufacturer : </td>
										<td style="padding-left:10px;"><input type="text" name="n_brand" value="<?=set_value('n_brand',isset($record[0]->V_Manufacturer) || isset($record[0]->V_Brandname) ? $record[0]->V_Brandname.'/'.$record[0]->V_Manufacturer : '')?>" id="n_brand" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Description  : </td>
										<td style="padding-left:10px;"><input type="text" name="n_description" value="<?=set_value('n_description',isset($record[0]->V_Asset_name) ? $record[0]->V_Asset_name : '')?>" id="n_description" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Model  : </td>
										<td style="padding-left:10px;"><input type="text" name="n_model" value="<?=set_value('n_model',isset($record[0]->V_Model_no) ? $record[0]->V_Model_no : '')?>" id="n_model" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Asset Tag Number : </td>
										<td style="padding-left:10px;"><input type="text" name="n_assettag" value="<?=set_value('n_assettag',isset($record[0]->V_Tag_no) ? $record[0]->V_Tag_no : '')?>" id="n_assettag" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Asset Number : </td>
										<td style="padding-left:10px;"><input type="text" name="n_assetnumber" value="<?=set_value('n_assetnumber',isset($record[0]->V_Asset_no) ? $record[0]->V_Asset_no : '')?>" id="n_assetnumber" class="form-control-button n_wi-eq3" readonly> <span class="icon-question-circle" onclick="fCallRequestA()" value="Norequest"></span></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Asset Serial Number : </td>
										<td style="padding-left:10px;"><input type="text" name="n_assetserial" value="<?=set_value('n_assetserial',isset($record[0]->V_Serial_no) ? $record[0]->V_Serial_no : '')?>" id="n_assetserial" class="form-control-button n_wi-date2" readonly> </td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Purchase Cost : </td>
										<td style="padding-left:10px;"><input type="text" name="n_purchasecost" value="<?=set_value('n_purchasecost',isset($record[0]->N_Cost) ? $record[0]->N_Cost : '')?>" id="n_purchasecost" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Purchase Date : </td>
										<td style="padding-left:10px;"><input type="text" name="n_purchasedate" value="<?=set_value('n_purchasedate',isset($record[0]->V_PO_date) ? date("d-m-Y",strtotime($record[0]->V_PO_date)) : '')?>" id="n_purchasedate"  class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Age   : </td>
										<td style="padding-left:10px;"><input type="text" name="n_age" value="<?=set_value('n_age',isset($record[0]->V_PO_date) ? date("d-m-Y",strtotime($record[0]->V_PO_date)) : '')?>" id="n_age" class="form-control-button n_wi-date2" readonly></td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>
			</div>
			<div class="ui-main-form-5">
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Components & Attachments</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding:10px; width:15%;" valign="top">Components  :   </td>
										<?php if ($this->input->get('mrinno') == ''){ ?>
										<td style="padding:10px;"><a href="javascript:void(0)" onclick="fCallLocationa('<?=$runningno?>','component')" value="z" ><span class="icon-plus" style="font-size:12px; color:green;" ></span> Add New </a></td>
										<?php } else { ?>
										<td style="padding:10px;"><a href="javascript:void(0)" onclick="fCallLocationa('<?=$this->input->get('mrinno')?>','component')" value="z" ><span class="icon-plus" style="font-size:12px; color:green;" ></span> Add New </a></td>
										<?php } ?>
									</tr>

									<tr style="display:<?=($this->uri->slash_segment(1) != 'mrinnew_ctrl/') && $this->input->get('pro') == 'new' ? 'none' : 'block' ?>;" id="trcommacomponent">
										<td style="padding-left:10px; display:block;">
										<?php if ($this->uri->slash_segment(1) != 'mrinnew_ctrl/' && $this->input->get('pro') == 'new') { ?>
										<span style="display:inline-block;" id="spcommacomponent"></span>
										<?php } else { ?>
										<span style="display:inline-block;" id="spcommacomponent"></span>
										<span id="spcomponent">
										<?php
											foreach($recordcom as $row){
												$extension = explode(".",$row->com_id);

												if ($extension[1] == 'docx' || $extension[1] == 'xlsx' || $extension[1] == 'pdf') {
												echo "<span class='icon-play icon' style='font-size:15px;'></span><span style='font-size:15px; font-weight:bold;'>" .$row->component_name. "</span><a href=".base_url()."uploadmrinfiles/".$row->com_id."><span class='icon-file-text2 icon'></a></span><a href='javascript:fCallLocatiod(\"".$row->asset_no."\",\"".$row->Id."\",\"component\");'><span class='icon-cross icon' style='color:red;'></span></a><a href='javascript:fCallLocatioe(\"".$row->asset_no."\",\"".$row->Id."\",\"component\");'><span class='icon-new icon'></span></a>";
												echo '<br>';
												} else {
												echo "<span class='icon-play icon' style='font-size:15px;'></span><span style='font-size:15px; font-weight:bold;'>" .$row->component_name. "</span> <br/><img src=".base_url()."uploadmrinfiles/".$row->com_id." style='width:50px; height:50px; padding-left:5px;' ><a href='javascript:fCallLocatiod(\"".$row->asset_no."\",\"".$row->Id."\",\"component\");'><span class='icon-cross icon' style='color:red;'></span></a><a href='javascript:fCallLocatioe(\"".$row->asset_no."\",\"".$row->Id."\",\"component\");'><span class='icon-new icon'></span></a>";
												echo '<br>';
												}
											}
										?>
										<?php } ?>
										</span>
										</td>
									</tr>
									
									<tr>
										<td style="padding:10px;" valign="top">Attachments   :   </td>
										<!--<td style="padding:10px;"><a href="" ><span class="icon-plus" style="font-size:12px; color:green;"></span> Add New</a></td>-->
										<?php if ($this->input->get('mrinno') == ''){ ?>
										<td style="padding:10px;"><a href="javascript:void(0)" onclick="fCallLocationa('<?=$runningno?>','attachment')" value="z" ><span class="icon-plus" style="font-size:12px; color:green;" ></span> Add New </a></td>
										<?php } else { ?>
										<td style="padding:10px;"><a href="javascript:void(0)" onclick="fCallLocationa('<?=$this->input->get('mrinno')?>','attachment')" value="z" ><span class="icon-plus" style="font-size:12px; color:green;" ></span> Add New </a></td>
										<?php } ?>
									</tr>
									<tr style="display:<?=($this->uri->slash_segment(1) != 'mrinnew_ctrl/') && $this->input->get('pro') == 'new' ? 'none' : 'block' ?>;" id="trcommaattachment">
										<td style="padding-left:10px; display:block;">
										<?php if ($this->uri->slash_segment(1) != 'mrinnew_ctrl/' && $this->input->get('pro') == 'new') { ?>
										<span style="display:inline-block;" id="spcommaattachment"></span>
										<?php } else { ?>
										<span style="display:inline-block;" id="spcommaattachment"></span>
										<span id="spattachment">
										<?php
											foreach($recordatt as $row){
												$extension = explode(".",$row->doc_id);

												if ($extension[1] == 'docx' || $extension[1] == 'xlsx' || $extension[1] == 'pdf') {
												echo "<span class='icon-play icon' style='font-size:15px;'></span><span style='font-size:15px; font-weight:bold;'>" .$row->Doc_name. "</span><a href=".base_url()."uploadmrinfiles/".$row->doc_id."><span class='icon-file-text2 icon'></a></span><a href='javascript:fCallLocatiod(\"".$row->asset_no."\",\"".$row->Id."\",\"attachment\");'><span class='icon-cross icon' style='color:red;'></span></a><a href='javascript:fCallLocatioe(\"".$row->asset_no."\",\"".$row->Id."\",\"attachment\");'><span class='icon-new icon'></span></a>";
												echo '<br>';
												} else {
												echo "<span class='icon-play icon' style='font-size:15px;'></span><span style='font-size:15px; font-weight:bold;'>" .$row->Doc_name. "</span> <br/><img src=".base_url()."uploadmrinfiles/".$row->doc_id." style='width:50px; height:50px; padding-left:5px;' ><a href='javascript:fCallLocatiod(\"".$row->asset_no."\",\"".$row->Id."\",\"attachment\");'><span class='icon-cross icon' style='color:red;'></span></a><a href='javascript:fCallLocatioe(\"".$row->asset_no."\",\"".$row->Id."\",\"attachment\");'><span class='icon-new icon'></span></a>";
												echo '<br>';
												}
											}
										?>
										<?php } ?>
										</span>
										</td>
									</tr>									
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<div class="ui-main-form-5">
				<div class="middle_d">
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Item Specification</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding:10px; width:8%;" valign="top">Item(s)  :   </td>
										<td style="padding:10px;">
											<table class="wnctable" border="1" id="myTable">
												<tr>
													<th>No</th>
													<th style="width:100px;">Item Code</th>
													<th style="width:300px;">Item Name</th>
													<th>Qty Req</th>
													<th>Reimbursable</th>
													<th>Last Replaced<br/>(MM/DD/YYYY)</th>
													<?php if ($this->input->get('pro') != 'edit') { ?>
													<th style="width:140px;">Price</th>
													<th>Vendor</th>
													<?php } ?>
												</tr>
												<?php if ($this->input->get('pro') == 'edit') { ?>
												<?php $numrow = 1; foreach ($recordis as $item): ?>
													<tr>
														<td><?=$numrow?><input type="hidden" name="rows" value="<?=$numrow?>"></td>
														<td><p id="itemcode<?=$numrow?>"><?=isset($item->ItemCode) ? $item->ItemCode : ''?></p><input type="hidden" id="itemcodei<?=$numrow?>" name="itemcode<?=$numrow?>" value="<?=isset($item->ItemCode) ? $item->ItemCode : ''?>"></td>
														<td><?=isset($item->ItemName) ? $item->ItemName : ''?></td>
														<td><input type="text" name="n_qty<?=$numrow?>" value="<?=isset($item->Qty) ? $item->Qty : ''?>" class="form-control-button2" style=width:100px;"></td>
														<td><select name="a_rem<?=$numrow?>" class="dropdown"><option value="" <?=isset($item->Reimbursable) && $item->Reimbursable == 0 ? 'selected="selected"' : 'selected="selected"'?>>None</option><option value="1" <?=isset($item->Reimbursable) && $item->Reimbursable == 1 ? 'selected="selected"' : ''?>>Mishandling</option><option value="2" <?=isset($item->Reimbursable) && $item->Reimbursable == 2 ? 'selected="selected"' : ''?>>Supplementary</option><option value="3" <?=isset($item->Reimbursable) && $item->Reimbursable == 3 ? 'selected="selected"' : ''?>>Upgrading</option><option value="4" <?=isset($item->Reimbursable) && $item->Reimbursable == 4 ? 'selected="selected"' : ''?>>Re-Installation</option><option value="5" <?=isset($item->Reimbursable) && $item->Reimbursable == 5 ? 'selected="selected"' : ''?>>Other</option></select></td>
														<td><INPUT TYPE="text" name="startDate<?=$numrow?>" value="<?=isset($item->LastRepDt) ? date("m/d/Y",strtotime($item->LastRepDt)) : ''?>" class="form-control-button2" style=width:100px;" onChange="validDate(this)"></td>
														<input type="hidden" name="id<?=$numrow?>" value="<?=isset($item->Id) ? $item->Id : ''?>">
													</tr>
												<?php $numrow++?>
												<?php endforeach; ?>
												<?php } ?>
											</table>
											<a href="javascript:void(0)" onclick="fCallitem()" style="padding-top:10px; display:block; width:100px;"><span class="icon-plus" style="font-size:12px; color:green;" ></span> Add New </a>
										</td>
									</tr>						
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center">
						<input type="submit" class="btn-button btn-primary-button" name="mysubmit" value="Save" style="width:150px;"/>
						<input type="button" class="btn-button btn-primary-button" name="Cancel" value="Cancel" onclick="window.history.back()" style="width:150px;"/>
					</td>
				</tr>
			</table>
			<?php echo form_hidden('tempno',isset($runningno) ? $runningno : '') ?>
			<?php echo form_hidden('ApprStatusID',isset($record[0]->ApprStatusID) ? $record[0]->ApprStatusID : '') ?>
			<?php echo form_hidden('DateApproval',isset($record[0]->DateApproval) ? $record[0]->DateApproval : '') ?>
			<?php echo form_hidden('ApprStatusIDx',isset($record[0]->ApprStatusIDx) ? $record[0]->ApprStatusIDx : NULL) ?>
			<?php echo form_hidden('DateApprovalx',isset($record[0]->DateApprovalx) ? $record[0]->DateApprovalx : '') ?>
			<?php echo form_hidden('ApprStatusIDxx',isset($record[0]->ApprStatusIDxx) ? $record[0]->ApprStatusIDxx : NULL) ?>
			<?php echo form_hidden('DateApprovalxx',isset($record[0]->DateApprovalxx) ? $record[0]->DateApprovalxx : '') ?>
			<?php echo form_hidden('class_id',isset($user[0]->class_id) ? $user[0]->class_id : '') ?>
		</div>
	</div>
</div>
<style>
	.icon{
	 font-size:14px;
	 margin-right:5px;
	 margin-left:5px;
	 display:iniline-block;
	}
	.icon2{
	 font-size:14px;
	 margin-left:5px;
	 color:green;
	}
</style>
<script></script>
</body>
<?php include 'content_jv_popup.php';?>
<?php echo form_close(); ?>
</html>
