<?php
if ($this->input->get('ex') == 'excel'){
$filename ="Complaint Level.xls";
header('Content-type: application/ms-excel');
header('Content-Disposition: attachment; filename='.$filename);
}
?>
<?php if ($this->input->get('ex') == ''){?>
<div id="Instruction" class="pr-printer">
    <div class="header-pr">
	Complaint Level Compiled by Day And Hour
	</div>
     <button onclick="javascript:myFunction('complaintlevel?m=<?=$month?>&y=<?=$year?>&none=closed&ex=ex');" class="btn-button btn-primary-button">PRINT</button>
    <button type="cancel" class="btn-button btn-primary-button" onclick="location.href = '<?php base_url();?>Schedule';">CANCEL</button>
	<?php if (($this->input->get('ex') == '') or ($this->input->get('none') == '')){?>
	<a href="<?php echo base_url();?>index.php/contentcontroller/complaintlevel?&ex=excel&none=close" style="float:right; margin-right:40px;"><img src="<?php echo base_url();?>images/excel.png" style="width:40px; height:38px; position:absolute;" title="export to excel"></a>
	<?php } ?>
</div>
<?php } ?>
<div class="menu" style="position:relative;">
<?php if (($this->input->get('ex') == '') or ($this->input->get('none') == 'closed')){?>
<?php include 'content_headprint.php';?>
<?php } ?>

<div class="m-div">
	<table class="rport-header">
		<tr>
			<td colspan="5">Complaint Levels Compiled by Day And Hour - <?php echo $this->session->userdata('usersessn');?></td>
		</tr>
	</table>
</form>
</div>
<div class="m-div">
	<table class="tftable" border="1" style="text-align:center;">
		<tr>
			<th colspan="3">Crime/Complaint Occurred</th>
			<th colspan="7">Day of The Week When Occurred</th>
		</tr>
		<tr>
			<th>Time</th>
			<th>Number</th>
			<th>Percent</th>
			<th>Sun</th>
			<th>Mon</th>
			<th>Tues</th>
			<th>Wed</th>
			<th>Thurs</th>
			<th>Fri</th>
			<th>Sat</th>
		</tr>
		<tr>
			<td>0001-0100</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0100-0200</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0200-0300</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0300-0400</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0400-0500</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0500-0600</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0600-0700</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0700-0800</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0800-0900</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>0900-1000</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1000-1100</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1100-1200</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1200-1300</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1300-1400</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1400-1500</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1500-1600</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1600-1700</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1700-1800</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1800-1900</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>1900-2000</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>2000-2100</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>2100-2200</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>2200-2300</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>2300-2400</td>
			<td>61</td>
			<td>6.2</td>
			<td>12</td>
			<td>5</td>
			<td>4</td>
			<td>6</td>
			<td>2</td>
			<td>2</td>
			<td>12</td>
		</tr>
		<tr>
			<td>Total</td>
			<td>2006</td>
			<td></td>
			<td>120</td>
			<td>50</td>
			<td>40</td>
			<td>60</td>
			<td>20</td>
			<td>20</td>
			<td>120</td>
		</tr>
		<tr>
			<td>Percentage</td>
			<td></td>
			<td>100.00</td>
			<td>12.0</td>
			<td>50.0</td>
			<td>40.0</td>
			<td>60.0</td>
			<td>20.0</td>
			<td>20.0</td>
			<td>120.0</td>
		</tr>
		<tr>
			<td colspan="10" class="tb-avg">
			Of all complaints reported, 3.1 percent occurred between 0001-0100 hours. Of the total number of 61 complaints occurring these hours, 9 occurred on Saturday.
			</td>
		</tr>
	</table>
	<style>
	.tb-avg{text-align:left;padding-left:10px;}
	</style>
</div>
<?php if (($this->input->get('ex') == '') or ($this->input->get('none') == 'closed')){?>
	<table width="99%" border="0">
		<tr>
			<td valign="top" colspan="2"><hr color="black" size="1Px"></td>
		</tr>
		<tr>
			<td width="50%">Complaint Level Compiled by Day And Hour</td>
			<td width="50%" align="right"><i>Computer Generated - APBESys</i></td>
		</tr>
	</table>
<?php } ?>
<?php if (($this->input->get('ex') == '') or ($this->input->get('none') == 'closed')){?>
<?php include 'content_footerprint.php';?>
<?php } ?>
</div>
</div>

