<?php echo form_open('workorder_ctrl');?>
<?php $numberdate = 0; ?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p">&nbsp;</div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">New Request</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Request number will be automatically generated by the system.<br> <span style="color:red;"><?php echo validation_errors(); ?></span></div>
			<div class="ui-main-form-1">
				<div class="middle_d">
					<table width="100%" class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Request Details</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding-left:10px; padding-top:5px;" valign="top" class="ui-w">Request Type:</td>
											<td style="padding-left:10px; padding-top:5px;" valign="top">	
												<?php if ($this->session->userdata('usersess')=='HKS' OR $this->session->userdata('usersess')=='SEC') {?>
												<input type="radio" id="radio-1-4" name="n_request_type" class="regular-radio" value="A4" <?php echo set_radio('n_request_type', 'A4'); ?>/>   
												<label for="radio-1-4"></label> A4 - User Requests<br>
												<input type="radio" id="radio-1-5" name="n_request_type" class="regular-radio" value="A5" <?php echo set_radio('n_request_type', 'A5'); ?>/>   
												<label for="radio-1-5"></label> A5 - Investigation of Incidences<br>
												<input type="radio" id="radio-1-7" name="n_request_type" class="regular-radio" value="A7" <?php echo set_radio('n_request_type', 'A7'); ?>/>   
												<label for="radio-1-7"></label> A7 - User Training<br>
												<input type="radio" id="radio-1-9" name="n_request_type" class="regular-radio" value="A9" <?php echo set_radio('n_request_type', 'A9'); ?>/>   
												<label for="radio-1-9"></label> A9 - Internal Request<br>
												<input type="radio" id="radio-1-10" name="n_request_type" class="regular-radio" value="A10" <?php echo set_radio('n_request_type', 'A10'); ?>/>   
												<label for="radio-1-10"></label> A10 - Reimbursable Work<br>
												<?php } else { ?>
												<input type="radio" id="radio-1-1" name="n_request_type" class="regular-radio" value="A1" <?php echo set_radio('n_request_type', 'A1',true); ?>/>   
												<label for="radio-1-1"></label> A1 - Breakdown Maintenance (BM)<br>
												<input type="radio" id="radio-1-2" name="n_request_type" class="regular-radio" value="A2" <?php echo set_radio('n_request_type', 'A2'); ?>/>   
												<label for="radio-1-2"></label> A2 - Schedule Corrective Maintenance (SCM)<br>
												<input type="radio" id="radio-1-3" name="n_request_type" class="regular-radio" value="A3" <?php echo set_radio('n_request_type', 'A3'); ?>/>   
												<label for="radio-1-3"></label> A3 - Corrective Maintenance (CM)<br>
												<input type="radio" id="radio-1-4" name="n_request_type" class="regular-radio" value="A4" <?php echo set_radio('n_request_type', 'A4'); ?>/>   
												<label for="radio-1-4"></label> A4 - User Requests<br>
												<input type="radio" id="radio-1-5" name="n_request_type" class="regular-radio" value="A5" <?php echo set_radio('n_request_type', 'A5'); ?>/>   
												<label for="radio-1-5"></label> A5 - Investigation of Incidences<br>
												<input type="radio" id="radio-1-6" name="n_request_type" class="regular-radio" value="A6" <?php echo set_radio('n_request_type', 'A6'); ?>/>   
												<label for="radio-1-6"></label> A6 - Technical Advice<br>
												<input type="radio" id="radio-1-7" name="n_request_type" class="regular-radio" value="A7" <?php echo set_radio('n_request_type', 'A7'); ?>/>   
												<label for="radio-1-7"></label> A7 - User Training<br>
												<input type="radio" id="radio-1-8" name="n_request_type" class="regular-radio" value="A8" <?php echo set_radio('n_request_type', 'A8'); ?>/>   
												<label for="radio-1-8"></label> A8 - Testing and Commissioning (T&C)<br>
												<input type="radio" id="radio-1-9" name="n_request_type" class="regular-radio" value="A9" <?php echo set_radio('n_request_type', 'A9'); ?>/>   
												<label for="radio-1-9"></label> A9 - Internal Request<br>
												<input type="radio" id="radio-1-10" name="n_request_type" class="regular-radio" value="A10" <?php echo set_radio('n_request_type', 'A10'); ?>/>   
												<label for="radio-1-10"></label> A10 - Reimbursable Work<br>
												<?php } ?>
												<!--<input type="radio" id="radio-1-8" name="n_request_type" class="regular-radio" value="A10" <?php echo set_radio('n_request_type', 'A10'); ?>/>   
												<label for="radio-1-8"></label> A10 - Technical Advice<br>
												<input type="radio" id="radio-1-9" name="n_request_type" class="regular-radio" value="A11" <?php echo set_radio('n_request_type', 'A11'); ?>/>   
												<label for="radio-1-9"></label> A11 - User Training<br>
												<input type="radio" id="radio-1-10" name="n_request_type" class="regular-radio" value="A12" <?php echo set_radio('n_request_type', 'A12'); ?>/>   
												<label for="radio-1-10"></label> A12 - Testing and Commissioning (T&C)<br>
												<input type="radio" id="radio-1-11" name="n_request_type" class="regular-radio" value="R1" <?php echo set_radio('n_request_type', 'R1'); ?>/>   
												<label for="radio-1-11"></label> R1 - Request for Yearly Planner<br>
												<input type="radio" id="radio-1-12" name="n_request_type" class="regular-radio" value="R2" <?php echo set_radio('n_request_type', 'R2'); ?>/>   
												<label for="radio-1-12"></label> R2 - Internal Request<br>-->
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Request Date :   </td>
											<td style="padding-left:10px;" valign="top"><input type="text"  id="date<?php echo $numberdate++; ?>" name="n_request_date" max="<?=date('Y-m-d')?>" value="<?php echo set_value('n_request_date'); ?>" class="form-control-button2 n_wi-date2"></td>
										</tr>
										<tr>
										<td style="padding-left:10px;" valign="top">Request&nbsp;Time&nbsp;:&nbsp;</td>
				            <td style="padding-left:10px;" valign="top">
										<?php 
										$hour_list = array(
															'0' => '0',
                  						'1' => '1',
                  				 		'2' => '2',
                  				 		'3' => '3',
                  						'4' => '4',
                  				 		'5' => '5',
                  				 		'6' => '6',
                  						'7' => '7',
                  				 		'8' => '8',
                  				 		'9' => '9',
                  						'10' => '10',
                  				 		'11' => '11',
                  				 		'12' => '12',
                  				 		'13' => '13',
                  				 		'14' => '14',
                  						'15' => '15',
                  				 		'16' => '16',
                  				 		'17' => '17',
                  						'18' => '18',
                  				 		'19' => '19',
                  				 		'20' => '20',
                  						'21' => '21',
                  				 		'22' => '22',
                  				 		'23' => '23',
                					 );
										 ?>
								        <?php echo form_dropdown('n_hour', $hour_list, set_value('n_hour',date('H')) , 'class="dropdown" style="width: 52px;"'); ?> 
										<?php 
										$min_list = array(
															'0' => '0',
                  						'1' => '1',
                  				 		'2' => '2',
                  				 		'3' => '3',
                  						'4' => '4',
                  				 		'5' => '5',
                  				 		'6' => '6',
                  						'7' => '7',
                  				 		'8' => '8',
                  				 		'9' => '9',
                  						'10' => '10',
                  				 		'11' => '11',
                  				 		'12' => '12',
                  				 		'13' => '13',
                  				 		'14' => '14',
                  						'15' => '15',
                  				 		'16' => '16',
                  				 		'17' => '17',
                  						'18' => '18',
                  				 		'19' => '19',
                  				 		'20' => '20',
                  						'21' => '21',
                  				 		'22' => '22',
                  				 		'23' => '23',
                  						'24' => '24',
                  				 		'25' => '25',
                  				 		'26' => '26',
                  						'27' => '27',
                  				 		'28' => '28',
                  				 		'29' => '29',
                  						'30' => '30',
                  				 		'31' => '31',
                  				 		'32' => '32',
                  						'33' => '33',
                  				 		'34' => '34',
                  				 		'35' => '35',
                  				 		'36' => '36',
                  				 		'37' => '37',
                  						'38' => '38',
                  				 		'39' => '39',
                  				 		'40' => '40',
                  						'41' => '41',
                  				 		'42' => '42',
                  				 		'43' => '43',
                  						'44' => '44',
                  				 		'45' => '45',
                  				 		'46' => '46',
                  				 		'47' => '47',
                  				 		'48' => '48',
                  						'49' => '49',
                  				 		'50' => '50',
                  				 		'51' => '51',
                  				 		'52' => '52',
                  				 		'53' => '53',
                  						'54' => '54',
                  				 		'55' => '55',
                  				 		'56' => '56',
                  						'57' => '57',
                  				 		'58' => '58',
                  				 		'59' => '59',
                					 );
										 ?>		
		              			<?php echo form_dropdown('n_min', $min_list, set_value('n_min',date('i')) , 'class="dropdown" style="width: 52px;"'); ?> 
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Priority :  </td>
											<td style="padding-left:10px;" valign="top">	
												<input type="radio" id="radio-1-13" name="n_priority" class="regular-radio" value="Normal" <?php echo set_radio('n_priority', 'Normal',TRUE); ?>/>   
												<label for="radio-1-13"></label> Normal<br>
												<input type="radio" id="radio-1-14" name="n_priority" class="regular-radio" value="Emergency" <?php echo set_radio('n_priority', 'Emergency'); ?>/>   
												<label for="radio-1-14"></label><span style="color:red;"> Emergency</span><br>
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Summary : </td>
											<td style="padding-left:10px;"><textarea class="Input n_com2" name="n_summary" cols="17" rows="6"><?php echo set_value('n_summary'); ?></textarea></td>
										</tr>																																			
									</table>
								</td>
							</tr>
					</table>
				</div>
				
				<div class="middle_d">
					<?php if ($this->session->userdata('usersess')=='BES' OR $this->session->userdata('usersess')=='FES') {?>
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Related Asset (Compulsory For A4 Request)</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Asset Number :   </td>
										<td style="padding-left:10px;" width=""><input type="text" id="n_asset_number" name="n_asset_number" value="<?php echo set_value('n_asset_number'); ?>" class="form-control-button2 n_wi-eq3" readonly> <span class="icon-windows" onclick="fCallassetsnumber(this)" value="desk"></span></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Tag Number :   </td>
										<td style="padding-left:10px;"><input type="text" id="n_tag_number" name="n_tag_number"  value="<?php echo set_value('n_tag_number'); ?>" class="form-control-button2 n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Serial Number :  </td>
										<td style="padding-left:10px;"><input type="text" id="n_serial_number" name="n_serial_number" value="<?php echo set_value('n_serial_number'); ?>" class="form-control-button2 n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Name :	 </td>
										<td style="padding-left:10px;"><input type="text" id="n_name" name="n_name" value="<?php echo set_value('n_name'); ?>" class="form-control-button2 n_wi-date2" readonly></td>
									</tr>																																																																	
								</table>
							</td>
						</tr>						
					</table>
					<?php } ?>
				</div>

			</div>
			<div class="ui-main-form-2">
				<div class="middle_d">
					<table class="ui-content-form-reg" >
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Details of Related Request</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
																			<tr>
										<td style="padding-left:10px;" class="ui-w">Requested By : </td>
										<td style="padding-left:10px;" ><input type="text" name="n_requested" value="<?php echo set_value('n_requested'); ?>" class="form-control-button n_wi-date2"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Designation : </td>
										<td style="padding-left:10px; padding-top:5px;" valign="top">	
											<input type="radio" id="radio-1-15" name="n_designation" class="regular-radio" value = "Professor" <?php echo set_radio('n_designation', 'Professor', TRUE); ?>/>   
											<label for="radio-1-15"></label> Professor<br>
											<input type="radio" id="radio-1-16" name="n_designation" class="regular-radio" value = "Doctor" <?php echo set_radio('n_designation', 'Doctor'); ?>/>   
											<label for="radio-1-16"></label> Doctor<br>
											<input type="radio" id="radio-1-17" name="n_designation" class="regular-radio" value = "Matron" <?php echo set_radio('n_designation', 'Matron'); ?>/>   
											<label for="radio-1-17"></label> Matron<br>
											<input type="radio" id="radio-1-18" name="n_designation" class="regular-radio" value = "Medical Assistant" <?php echo set_radio('n_designation', 'Medical Assistant'); ?>/>   
											<label for="radio-1-18"></label> Medical Assistant<br>
											<input type="radio" id="radio-1-19" name="n_designation" class="regular-radio" value = "IIUM Officer" <?php echo set_radio('n_designation', 'IIUM Officer'); ?>/>   
											<label for="radio-1-19"></label> IIUM Officer<br>
											<input type="radio" id="radio-1-20" name="n_designation" class="regular-radio" value = "Sister In-Charge" <?php echo set_radio('n_designation', 'Sister In-Charge'); ?>/>   
											<label for="radio-1-20"></label> Sister In-Charge<br>
											<input type="radio" id="radio-1-21" name="n_designation" class="regular-radio" value = "Sister On Duty" <?php echo set_radio('n_designation', 'Sister On Duty'); ?>/>   
											<label for="radio-1-21"></label> Sister On Duty<br>
											<input type="radio" id="radio-1-22" name="n_designation" class="regular-radio" value = "Specialist" <?php echo set_radio('n_designation', 'Specialist'); ?>/>   
											<label for="radio-1-22"></label> Specialist<br>
											<input type="radio" id="radio-1-23" name="n_designation" class="regular-radio" value = "Staff Nurse" <?php echo set_radio('n_designation', 'Staff Nurse'); ?>/>   
											<label for="radio-1-23"></label> Staff Nurse<br>
											<input type="radio" id="radio-1-24" name="n_designation" class="regular-radio" value = "Supervisor" <?php echo set_radio('n_designation', 'Supervisor'); ?>/>   
											<label for="radio-1-24"></label> Supervisor<br>
											<input type="radio" id="radio-1-25" name="n_designation" class="regular-radio" value = "PMSB" <?php echo set_radio('n_designation', 'PMSB'); ?>/>   
											<label for="radio-1-25"></label> PMSB<br>
											<input type="radio" id="radio-1-26" name="n_designation" class="regular-radio" value = "APFMS" <?php echo set_radio('n_designation', 'APFMS'); ?>/>   
											<label for="radio-1-26"></label> APFMS<br>
											<input type="radio" id="radio-1-27" name="n_designation" class="regular-radio" value = "APSB" <?php echo set_radio('n_designation', 'APSB'); ?>/>   
											<label for="radio-1-27"></label> APSB
										</td>
									</tr>																																									
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Location</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table" style="padding-bottom: 8px;">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Phone Number :  </td>
										<td style="padding-left:10px;" ><input type="text" name="n_phone_number" id="n_phone_number" value="<?php echo set_value('n_phone_number'); ?>" class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fpop_location_user()"></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">User Department :   </td>
										<td style="padding-left:10px;"><input type="text" id="n_user_department" name="n_user_department" value="<?php echo set_value('n_user_department'); ?>"  class="form-control-button n_wi-eq3" readonly> <span class="icon-windows" onclick="fCalllocation()" ></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" id="n_user_department1" name="n_user_department1" value="<?php echo set_value('n_user_department1'); ?>" class="form-control-button n_wi-date2"  readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Location : </td>
										<td style="padding-left:10px;"><input type="text" id="n_location" name="n_location" value="<?php echo set_value('n_location'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" id="n_location2" name="n_location1" value="<?php echo set_value('n_location1'); ?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>	
									<tr>
										<td style="padding-left:10px;">Latest Work Order </td>
										<td style="padding-left:10px;"><span class="icon-windows" onclick="rel()" value=""></span></td>
									</tr>			
								</table>
							</td>
						</tr>					
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Work Order</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Print Work Order: </td>
										<td style="padding-left:10px;" >
										<input type="checkbox" name="chkbox" value="ON" id ="checkbox" <?php echo set_checkbox('chkbox', 'ON'); ?>
										</td>
									</tr>																																																													
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center"><input type="submit" class="btn-button btn-primary-button" style="width: 200px;" name="mysubmit" value="Confirm"></td>
				</tr>
			</table>
			<?php echo form_hidden('parent',$this->input->get('parent'));?>
		</div>
	</div>
</div>
</body>
<?php include 'content_jv_popup.php';?>
<?php echo form_close(); ?>
</html>
