<?php echo form_open('workorder_ctrl/confirmation_workorder');?>
<div class="ui-middle-screen">
	<div class="content-workorder">
		<div class="div-p"></div>
		<div class="ui-main-form">
			<div class="ui-main-form-header">
				<table align="center" height="40px" border="0">
					<tr>
						<td><span style="margin-left:10px;">Confirm New Request</span></td>
					</tr>
				</table>
			</div>
			<div class="n-req">Request number will be automatically generated by the system.</div>
			<div class="ui-main-form-1">
				<div class="middle_d">
					<table width="100%" class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
								<td colspan="2" class="ui-header-new"><b>Request Details</b></td>
							</tr>
							<tr >
								<td class="ui-desk-style-table">
									<table class="ui-content-form" width="100%" border="0">
										<tr>
											<td style="padding-left:10px;" valign="top" class="ui-w">Request Type:</td>
											<td style="padding-left:10px;" valign="top" ><input type="text" name="n_request_type" value="<?php echo $this->input->post('n_request_type');?>" class="form-control-button2 n_wi-date2" readonly/></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Request Date :   </td>
											<td style="padding-left:10px;" valign="top"> <input type="text" name="n_request_date"  value="<?php echo set_value('n_request_date'); ?>" class="form-control-button2 n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Request Time :   </td>
											<td style="padding-left:10px;" valign="top"> <input type="text" name="n_hourmin"  value="<?php echo set_value('n_hour'); ?>:<?php echo str_pad(set_value('n_min'), 2, 0, STR_PAD_LEFT); ?>" class="form-control-button2 n_wi-date2" readonly></td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Priority :  </td>
											<td style="padding-left:10px;" valign="top"><input type="text" name="n_priority"  value="<?php echo $this->input->post('n_priority');?>" class="form-control-button2 n_wi-date2" readonly/>
											</td>
										</tr>
										<tr>
											<td style="padding-left:10px;" valign="top">Summary : </td>
											<td style="padding-left:10px;"><textarea class="Input" name="n_summary n_com2" readonly><?php echo set_value('n_summary'); ?></textarea></td>
										</tr>																																			
									</table>
								</td>
							</tr>
					</table>
				</div>
				<div class="middle_d">
					<?php if ($this->session->userdata('usersess')=='BES' OR $this->session->userdata('usersess')=='FES') {?>
					<table class="ui-content-form-reg">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Related Asset (Compulsory For Request A3 - A10)</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" style="color:black;" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Asset Number :   </td>
										<td style="padding-left:10px;" ><input type="text" name="n_asset_number" value="<?php echo $this->input->post('n_asset_number');?>" class="form-control-button2 n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Tag Number :   </td>
										<td style="padding-left:10px;"><input type="text" name="n_tag_number" value="<?php echo $this->input->post('n_tag_number');?>" class="form-control-button2 n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Serial Number :  </td>
										<td style="padding-left:10px;"><input type="text" name="n_serial_number" value="<?php echo $this->input->post('n_serial_number');?>" class="form-control-button2 n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Name :	 </td>
										<td style="padding-left:10px;"><input type="text" name="n_name" value="<?php echo $this->input->post('n_name');?>" class="form-control-button2 n_wi-date2" readonly/></td>
									</tr>																																																																	
								</table>
							</td>
						</tr>						
					</table>
					<?php } ?>
				</div>
			</div>
			<div class="ui-main-form-2">
				<div class="middle_d">
					<table class="ui-content-form-reg" >
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Details of Related Request</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Requested By : </td>
										<td style="padding-left:10px;" ><input type="text" name="n_requested" value="<?php echo $this->input->post('n_requested');?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>
									<tr>
										<td style="padding-left:10px;" valign="top">Designation : </td>
										<td style="padding-left:10px; padding-top:5px;" valign="top"><input type="text" name="n_designation" value="<?php echo $this->input->post('n_designation');?>" class="form-control-button n_wi-date2" readonly></td>
									</tr>																																									
								</table>
							</td>
						</tr>
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr class="ui-color-contents-style-1" height="30px">
							<td colspan="2" class="ui-header-new"><b>Location</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table" style="padding-bottom: 8px;">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Phone Number :  </td>
										<td style="padding-left:10px;"><input type="text" name="n_phone_number" value="<?php echo $this->input->post('n_phone_number');?>" class="form-control-button n_wi-date2" readonly /></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">User Department :   </td>
										<td style="padding-left:10px;"><input type="text" name="n_user_department" value="<?php echo $this->input->post('n_user_department');?>" class="form-control-button n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" name="n_location1" value="<?php echo $this->input->post('n_user_department1');?>" class="form-control-button n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">Location : </td>
										<td style="padding-left:10px;"><input type="text" name="n_location" value="<?php echo $this->input->post('n_location');?>" class="form-control-button n_wi-date2" readonly/></td>
									</tr>
									<tr>
										<td style="padding-left:10px;">&nbsp; </td>
										<td style="padding-left:10px;"><input type="text" name="n_location1" value="<?php echo $this->input->post('n_location1');?>" class="form-control-button n_wi-date2" readonly/></td>
									</tr>																																					
								</table>
							</td>
						</tr>						
					</table>
				</div>
				<div class="middle_d">
					<table class="ui-content-form-reg" style="">
						<tr style="color:white;" height="30px">
							<td colspan="2" class="ui-header-new"><b>Work Order</b></td>
						</tr>
						<tr >
							<td class="ui-desk-style-table">
								<table class="ui-content-form" width="100%" border="0">
									<tr>
										<td style="padding-left:10px;" class="ui-w">Print Work Order: </td>
										<td style="padding-left:10px;">
										<input type="checkbox" name="chkbox" id="checkbox" <?php echo set_checkbox('chkbox', 'ON', TRUE); ?> disabled>
										</td>
									</tr>																																																													
								</table>
							</td>
						</tr>						
					</table>
				</div>
			</div>
			<table align="center" height="40px" border="0" style="width:100%;" class="ui-main-form-footer">
				<tr>
					<td align="center">
						<input type="submit" class="btn-button btn-primary-button" name="mysubmit" value="Save" style="width:150px;"/>
						<input type="button" class="btn-button btn-primary-button" name="Cancel" value="Cancel" onclick="window.history.back()" style="width:150px;"/>
					</td>
				</tr>
			</table>
		</div>
	<?php echo form_hidden('n_request_type',$this->input->post('n_request_type'));?>
	<?php echo form_hidden('n_request_date',date('y-m-d',strtotime($this->input->post('n_request_date'))));?>
	<?php echo form_hidden('n_priority',$this->input->post('n_priority'));?>
	<?php echo form_hidden('V_servicecode',$this->session->userdata('usersess'));?>
	<?php echo form_hidden('n_summary',$this->input->post('n_summary'));?>
	<?php echo form_hidden('n_asset_number',$this->input->post('n_asset_number'));?>
	<?php echo form_hidden('n_tag_number',$this->input->post('n_tag_number'));?>
	<?php echo form_hidden('n_serial_number',$this->input->post('n_serial_number'));?>
	<?php echo form_hidden('n_name',$this->input->post('n_name'));?>
	<?php echo form_hidden('n_requested',$this->input->post('n_requested'));?>
	<?php echo form_hidden('V_User_dept_code',$this->input->post('V_User_dept_code'));?>
	<?php echo form_hidden('n_designation',$this->input->post('n_designation'));?>
	<?php echo form_hidden('n_phone_number',$this->input->post('n_phone_number'));?>
	<?php echo form_hidden('n_user_department',$this->input->post('n_user_department'));?>
	<?php echo form_hidden('n_location1',$this->input->post('n_location1'));?>
	<?php echo form_hidden('n_location',$this->input->post('n_location'));?>
	<?php echo form_hidden('n_location2',$this->input->post('n_location2'));?>
	<?php echo form_hidden('n_hour',$this->input->post('n_hour'));?>
	<?php echo form_hidden('n_min',$this->input->post('n_min'));?>
	<?php echo form_hidden('parent',$this->input->post('parent'));?>
	<?php echo form_hidden('chkbox',$this->input->post('chkbox'));?>
	</div>
</div>
</body>
<?php echo form_close(); ?>
</html>
